spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3308/btachdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #???? Batch Schema? ?????.
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    jdbc:
      initialize-schema: always
      #table-prefix: SYSTEM_
    #job? ???? ???, job? ??? ??? ??? ????? ???
    # ?? job? ??? ??? ?????? ??.
    job: #?? ?, ?? ??? ????? ?? Job? ??? ? ??.
      name: ${job.name:NONE} # ???? Job? ??? ????? arg? ??
      #?? ?? ??? NONE?? ??? ?? BatchJob? ???? ???.
      enabled: true

