spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3308/btachdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #???? Batch Schema? ?????.
  batch:
    jdbc:
      initialize-schema: always
      #table-prefix: SYSTEM_
    #job? ???? ???, job? ??? ??? ??? ????? ???
    # ?? job? ??? ??? ?????? ??.
    job: #?? ?, ?? ??? ????? ?? Job? ??? ? ??.
      name: ${job.name:NONE} # ???? Job? ??? ????? arg? ??
      #?? ?? ??? NONE?? ??? ?? BatchJob? ???? ???.
      enabled: true

